---
title: "Diversidad"
output: html_notebook
---

```{r}
library(tidyverse)
library(RColorBrewer)
library(vegan)
library(ggsignif)
library(glue)
library(measurements)
library(stringr)
```

```{r}
# convert lat/long from DMS to DEG
conv_to_deg <- function(dms_value) {
  dms <- sapply(dms_value, function(x) {
    dms_clean <- x %>%
      str_replace("°", "") %>%
      str_replace(",", " ") %>%
      str_split(" ", simplify = T)
    dms_clean[3] <- as.numeric(paste0("0.", dms_clean[3])) * 60
    
    paste(dms_clean, collapse = ' ')
  })
  
  return(as.numeric(conv_unit(dms, from = "deg_min_sec", to = "dec_deg")))
}
```

Carga de datos
```{r}
count_data <- read_tsv("abundance_table_genus_silva.tsv", show_col_types = FALSE) %>%
  column_to_rownames("tax") %>%
  select(-total) 
count_data_filtered <- read_tsv("abundance_table_genus_silva_filtered.tsv", show_col_types = FALSE) %>%
  column_to_rownames("tax") %>%
  t()
count_data_normalized <- read_tsv("abundance_table_genus_silva_normalized.tsv", show_col_types = FALSE) %>%
  column_to_rownames("tax") %>%
  t()

metadata <- read_tsv("metadata.tsv", show_col_types = FALSE)
```



# Curvas de rarefacción

```{r, fig.width=8, fig.height=6}
raremax <- min(colSums(count_data_filtered))
```


```{r, fig.width=8, fig.height=6}
# sin filtrar
rarecurve(count_data %>% t(), step = 100, sample=raremax, col = brewer.pal(8, "Set1"))
# filtrado
rarecurve(count_data_filtered, step = 100, sample=raremax, col = brewer.pal(8, "Set1"))
```

# Diversidad alfa

```{r}
data_richness <- estimateR(count_data_filtered)
data_evenness <- data.frame(Evenness=diversity(count_data_filtered) / log(specnumber(count_data_filtered)))
data_shannon <- data.frame(Shannon=diversity(count_data_filtered, index = "shannon"))

data_alphadiv <- bind_cols(metadata,  t(data_richness), data_shannon, data_evenness)
```

```{r, fig.width=8, fig.height=6}
alphadiv_values <- data_alphadiv %>%
  select(sample, sex, Richness=S.obs, Chao1=S.chao1 , Shannon, Evenness) %>%
  pivot_longer(-c(sample, sex), names_to = "metric", values_to = "value")

ggplot(alphadiv_values, aes(x=sex, y=value, fill=sex)) +
  geom_boxplot() +
  geom_point() +
  geom_signif(
    comparisons = list(c("Male", "Female")),
    test = wilcox.test#,
    # map_signif_level = TRUE
  ) +
  scale_y_continuous(expand = c(0.1, 0)) +
  scale_fill_brewer(palette="Set2") +
  theme_gray() +
  labs(x = element_blank(), y = element_blank()) +
  facet_wrap(~metric, scales = "free_y")
```

# Diversidad beta

```{r}
# bray curtis
bray_dist <- vegdist(count_data_normalized, method = "bray")
bray_pcoa <- cmdscale(bray_dist, eig=TRUE)
df_bray_pcoa <- bind_cols(metadata, as.data.frame(bray_pcoa$points))

# jaccard
jaccard_dist <- vegdist(count_data_normalized, method = "jaccard")
jaccard_pcoa <- cmdscale(jaccard_dist, eig=TRUE)
df_jaccard_pcoa <- bind_cols(metadata, as.data.frame(jaccard_pcoa$points))
```

# Porcentaje de varianza explicada
```{r}
calculate_variance_explained <- function(pcoa_object) {
  eigenvalues <- pcoa_object$eig
  total_variance <- sum(eigenvalues)
  var_explained <- eigenvalues / total_variance
 
  return(round(var_explained * 100, 2))
}

bray_expl_var <- calculate_variance_explained(bray_pcoa)
jaccard_expl_var <- calculate_variance_explained(jaccard_pcoa)
```

# Posición de mu
```{r}
ggplot(df_bray_pcoa, aes(x = V1, y = V2, color = sex, label = sample)) + 
  geom_point(size = 3) +
  geom_text(hjust=-0.2, vjust=-0.2, col="black") +
  theme_light() +
  labs(
    x = glue("PCoA Axis 1 ({bray_expl_var[1]}%)"),
    y = glue("PCoA Axis 2 ({bray_expl_var[2]}%)")
  )
```

