on:
  push:
    paths:
      - 'document/**.typ'
      - '.github/workflows/typst_compile.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v3

      - run: typst compile document/main.typ document.pdf
      
      - uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          add: 'document.pdf'
          message: Add compiled PDF
